scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: 
          - 'cadvisor:8080'
  - job_name: 'gpu_exporter'
    static_configs:
      - targets: 
          - 'prometheus_exporter_gpu:8000'
  - job_name: 'llm_models'
    static_configs:
      - targets: 
          - 'gemma3-4b-it:8000'
          - 'qwen3-4b:8000'
          - 'mistral-7b:8000'
  - job_name: 'litellm'
    static_configs:
      - targets:
          - 'litellm:4000'