- name: Create directory for monitoring
  file:
    path: /opt/monitoring/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy files for monitoring
  copy:
    src: monitoring/
    dest: /opt/monitoring/
    owner: root
    group: root
    mode: '0644'

- name: Create external Docker network for monitoring
  community.docker.docker_network:
    name: monitoring
    state: present

- name: Launch monitoring with Docker Compose
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring
    state: present
